[project]
name = "monitor_specific_file"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.7"

dependencies = [
    "boto3",
    "watchdog",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
